**Importing NumPy**

In [2]:
import numpy as np

print("Numpy version:" , np.__version__)

Numpy version: 2.1.3


**Creating Array from Python List**

In [3]:
import numpy as np

marks_list = [45, 60, 72, 88]

marks_array = np.array(marks_list)

print("List:", marks_list)
print("Array:", marks_array)
print("Type of List:", type(marks_list))
print("Type of array:", type(marks_array))

List: [45, 60, 72, 88]
Array: [45 60 72 88]
Type of List: <class 'list'>
Type of array: <class 'numpy.ndarray'>


**Example**

In [4]:
import numpy as np

temperature_list=[22, 25, 28, 30, 27]

temperature_array=np.array(temperature_list)

print("List:", temperature_list)
print("Array:", temperature_array)
print("Type of List:", type(temperature_list))
print("Type of Array:", type(temperature_array))

List: [22, 25, 28, 30, 27]
Array: [22 25 28 30 27]
Type of List: <class 'list'>
Type of Array: <class 'numpy.ndarray'>


**Using np.arange and np.linspace**

In [13]:
a = np.arange(0, 10, 2)
print("Arrange Array:", a)

b=np.linspace(0, 10, 2)
print("Linespace Array:", b)


Arrange Array: [0 2 4 6 8]
Linespace Array: [ 0. 10.]


**Example**

In [24]:
a=np.arange(2, 20, 2)
print("Arange Array:",a)

b=np.linspace(5, 10, 6)
print("Linspace Array:", b)

Arange Array: [ 2  4  6  8 10 12 14 16 18]
Linspace Array: [ 5.  6.  7.  8.  9. 10.]


**Zeros, Ones and Random Arrays**

In [39]:
zeros_arr = np.zeros((3, 3))     
ones_arr  = np.ones((2, 4))      
rand_arr  = np.random.rand(2, 3)

print("Zeros:\n", zeros_arr)
print("Ones:\n", ones_arr)
print("Random:\n", rand_arr)

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Random:
 [[0.62530059 0.1048192  0.87808297]
 [0.60605286 0.15067475 0.39798875]]


**Example**

In [43]:
zeros_arr = np.zeros((4, 4))     
ones_arr  = np.ones((3, 2))      
rand_arr  = np.random.rand(5)

print("Zeros:\n", zeros_arr)
print("Empty feature matrix for 4 students and 4 features.")
print("Ones:\n", ones_arr)
print("Default feature = 1 for some binary flags.")
print("Random:\n", rand_arr)
print("This could be random initial weights.")

Zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Empty feature matrix for 4 students and 4 features.
Ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Default feature = 1 for some binary flags.
Random:
 [0.99011512 0.05532575 0.27459752 0.76308088 0.40210738]
This could be random initial weights.


**Indexing & Slicing (1D and 2D)**

In [69]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[0])  
print(arr[2]) 
print(arr[-1])

print(arr[1:4])  
print(arr[:3])   
print(arr[2:])    
print(arr[::2])   

10
30
50
[20 30 40]
[10 20 30]
[30 40 50]
[10 30 50]


**Example**

In [63]:
a = np.array([5, 10, 15, 20, 25, 30])

print(a[0])
print(a[-2])
print(a[-1])
print(a[::3])
print(a[1:4])

5
25
30
[ 5 20]
[10 15 20]


**2D Arrays (Matrix) Indexing**

In [82]:
m = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Matrix:\n", m)

# element at row 0, column 1
print("m[0, 1] =", m[0, 1])  # 2

# second row (index 1)
print("Row 1:", m[1, :])     # [4 5 6]

# third column (index 2)
print("Column 2:", m[:, 2])  # [3 6 9]

# sub-matrix (top-left 2x2)
print("Sub-matrix:\n", m[0:2, 0:2])

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
m[0, 1] = 2
Row 1: [4 5 6]
Column 2: [3 6 9]
Sub-matrix:
 [[1 2]
 [4 5]]


**Example**

In [86]:
mat = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])

print("Matrix:\n", mat)

print("mat[2, 1] =", mat[2, 1])     # 100

print("Row 1:", mat[1, :])         # [50 60 70 80]

print("Last Column:", mat[:, 3])   # [40 80 120]

print("Sub-matrix:\n", mat[0:2, 0:3])

Matrix:
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
mat[2, 1] = 100
Row 1: [50 60 70 80]
Last Column: [ 40  80 120]
Sub-matrix:
 [[10 20 30]
 [50 60 70]]


**Arithmetic with Scalars**

In [89]:
arr = np.array([1, 2, 3, 4])

print("arr + 10 =", arr + 10)   # [11 12 13 14]
print("arr * 2  =", arr * 2)    # [2 4 6 8]
print("arr ** 2 =", arr ** 2)   # [1 4 9 16]
print("arr / 2  =", arr / 2)    # [0.5 1.  1.5 2. ]

arr + 10 = [11 12 13 14]
arr * 2  = [2 4 6 8]
arr ** 2 = [ 1  4  9 16]
arr / 2  = [0.5 1.  1.5 2. ]


**Example**

In [90]:
marks = np.array([40, 55, 63, 72, 90])

print("marks + 5 =", marks + 5)     # [45 60 68 77 95]

marks + 5 = [45 60 68 77 95]


**Element-wise Operations Between Arrays**

In [91]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("a + b =", a + b)    # [5 7 9]
print("a * b =", a * b)    # [4 10 18]

a + b = [5 7 9]
a * b = [ 4 10 18]


**Example**

In [93]:
x = np.array([2, 4, 6, 8])
y = np.array([1, 3, 5, 7])

# Compute and print the results
print("x + y =", x + y)
print("x - y =", x - y)
print("x * y =", x * y)

x + y = [ 3  7 11 15]
x - y = [1 1 1 1]
x * y = [ 2 12 30 56]


**Basic Statistics: min, max, mean**

In [92]:
data = np.array([10, 20, 35, 40, 50])

print("Min:", np.min(data))
print("Max:", np.max(data))
print("Mean:", np.mean(data))

Min: 10
Max: 50
Mean: 31.0


**Example**

In [94]:
arr = np.random.randint(0, 101, size=8)

print("Random Marks Array:", arr)
print("Minimum:", np.min(arr))
print("Maximum:", np.max(arr))
print("Average (mean):", np.mean(arr))

Random Marks Array: [75 45 37 21 98 37  5 46]
Minimum: 5
Maximum: 98
Average (mean): 45.5


**Mini Exercise: Simple Data Cleaning for AI**

In [95]:

# Simulated data values
values = np.array([15, 16, 200, 17, 16, 400, 15, 18])

print("Original values:", values)

# Step 1: Find mean and standard deviation
mean_val = np.mean(values)
std_val  = np.std(values)

print("Mean:", mean_val)
print("Std: ", std_val)

# Step 2: Replace very large values (> 100) with mean
cleaned = np.where(values > 100, mean_val, values)

print("Cleaned values:", cleaned)

Original values: [ 15  16 200  17  16 400  15  18]
Mean: 87.125
Std:  132.6880151897676
Cleaned values: [15.    16.    87.125 17.    16.    87.125 15.    18.   ]
